### ISSUE TITLE
Fi exited after making a Fi service request

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#21]
Opened Fi client.  Tapped "Build Network" and then "Request Fi Here".  Map was positioned over the default location (off the coast of Africa).  

Fi exited and I found the following Fi.txt file in my file system.  I tried a second time after GPS had located my position in Dallas.  The result I got after tapping "Request Fi Here" was different.  This time it took a few seconds and then a small gray system balloon appeared saying "Request Failed".   

java.lang.IllegalStateException: Fragment GoogleMapFragment{42a8a1e8} not attached to Activity
	at android.support.v4.app.Fragment.getResources(Fragment.java:619)
	at android.support.v4.app.Fragment.getString(Fragment.java:641)
	at com.fiandroid.view.fragment.GoogleMapFragment.handleMessage(GoogleMapFragment.java:304)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by dangtran89** [comment]
fixed in version 1.0.7
