### ISSUE TITLE
Tapping on Colovista Country Club Icon in 'map view' caused an exit - but no crash file 

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#23]
I have no debug data other than to track this.  It's happened twice and just started occurring.  

I am thinking it could be because the system is being worked on as I am testing - but regardless if there is an exception after tapping an icon then Fi should handle that without exit.  

Clarification:  I tapped on the Black Fi flag - not the merchant's Banner that appears after tapping the black flag.  Tapping the black flag caused the exit.

**Comment by vothanhkiet** [comment]
Which version you're running? Android or iOS ? Please provide software version and device's name.

**Comment by TarenJP** [comment]
Android 4.4.2

Samsung Note 2.

**Comment by dangtran89** [comment]
There is a FiTest.txt in  location sdcard/Fi/.
Please attach that file for me.
Thanks

**Comment by TarenJP** [comment]
This is what was in Fi directory.   I think it is an old file.   I always
see only 1 file.   Never more than one FiTest.txt.   Doea it overwrite or
should I see multiple files?
On Mar 16, 2015 10:52 PM, "dangtranVentuso" <notifications@github.com>
wrote:

> There is a FiTest.txt in location sdcard/Fi/.
> Please attach that file for me.
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ventuso/Fi-Test/issues/23#issuecomment-82082341>.
>

java.lang.SecurityException: Permission Denial: not allowed to send broadcast android.intent.action.MEDIA_MOUNTED from pid=8196, uid=10255
	at android.os.Parcel.readException(Parcel.java:1465)
	at android.os.Parcel.readException(Parcel.java:1419)
	at android.app.ActivityManagerProxy.broadcastIntent(ActivityManagerNative.java:2640)
	at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1659)
	at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:377)
	at com.fiandroid.restful.DownloadTask.onPostExecute(DownloadTask.java:121)
	at com.fiandroid.restful.DownloadTask.onPostExecute(DownloadTask.java:1)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by dangtran89** [comment]
This file is overwritten when crash happen . Please copy that files every it overwrite
